05.03.2017 19:21:51
System.AggregateException: One or more errors occurred. (No connection is available to service this operation: RPOP Commands; SocketClosed on 172.18.0.2:6379/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 35s ago, last-write: 35s ago, unanswered-write: 16468s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago) ---> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: RPOP Commands; SocketClosed on 172.18.0.2:6379/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 35s ago, last-write: 35s ago, unanswered-write: 16468s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago ---> StackExchange.Redis.RedisConnectionException: SocketClosed on 172.18.0.2:6379/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 35s ago, last-write: 35s ago, unanswered-write: 16468s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at socisaWorkers.Program.Main(String[] args)
---> (Inner Exception #0) StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: RPOP Commands; SocketClosed on 172.18.0.2:6379/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 35s ago, last-write: 35s ago, unanswered-write: 16468s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago ---> StackExchange.Redis.RedisConnectionException: SocketClosed on 172.18.0.2:6379/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 35s ago, last-write: 35s ago, unanswered-write: 16468s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)<---

=====================================================
